---
kind: pipeline
name: default

steps:

  - name:  fetch-schemas
    image: alpine/git:1.0.7
    commands:
      - git submodule update --init
      - test -f lib/schemas/README.md

  - name:  generate-ruby
    image: library/node:12.2-alpine
    commands:
      - npm install -g quicktype@15.0.194
      - mkdir -p src/azure-schema
      - quicktype \
          --src lib/schemas/ \
          --out src/azure-schema/schema.rb

